import {
  ArrowUpDown,
  Combine,
  Crop,
  Eraser,
  Expand,
  FileImage,
  FileOutput,
  FilePen,
  FileSearch,
  FileStack,
  FileText,
  FlipHorizontal,
  FlipHorizontal2,
  GalleryHorizontalEnd,
  Image,
  ImageDown,
  ImagePlus,
  Images,
  ListOrdered,
  Minimize2,
  RefreshCw,
  RotateCw,
  Scaling,
  Scissors,
  ShieldOff,
  Stamp,
  Trash2,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  FileText,
  Image,
  Combine,
  Minimize2,
  ImageDown,
  ImagePlus,
  FileImage,
  RotateCw,
  Scissors,
  Trash2,
  ArrowUpDown,
  Crop,
  Scaling,
  Images,
  FileOutput,
  ListOrdered,
  Stamp,
  Eraser,
  FileSearch,
  FilePen,
  ShieldOff,
  FlipHorizontal2,
  FlipHorizontal,
  GalleryHorizontalEnd,
  FileStack,
  RefreshCw,
  Expand,
};

export function Icon({
  name,
  ...props
}: { name: string } & React.ComponentProps<LucideIcon>) {
  const LucideIconComponent = icons[name] ?? FileText;
  return <LucideIconComponent {...props} />;
}
